### PR TITLE
Update scintillua lexers to tag scintillua_6.1

### PR DESCRIPTION
**Pull request by mcepl**
https://github.com/martanne/vis/pull/1018 has been fantastic achievement, but it was done against a bit older commit of https://github.com/orbitalquark/scintillua. This PR tries to sync `lexers/` directory to the same code as is the latest upstream tag https://github.com/orbitalquark/scintillua/releases/tag/scintillua_6.1.

Please, review, I am not sure how well I have to managed to do the merge.

Cc: @ninewise @Nomarian @qiu-x @jpe90 @deepcube @martanne @orbitalquark

### CODE REVIEW

**Comment by mcepl** [comment]
Hmm, so it is not complete yet. On the start of the editor I get immediately:

```
/home/matej/.config/vis/plugins/vis-toggler/init.lua:11: attempt to index a nil value (loc
al 'l')
```
(`vis-toggler` is obviously https://repo.or.cz/vis-toggler.git or from my clone of the repo on https://gitlab.com/mcepl/vis-toggler).

**Comment by jpe90** [comment]
For one thing it looks like [a change from upstream](https://github.com/orbitalquark/scintillua/commit/b1f72de6af355514ef0a394620aff86901ebfcc2) to `lexer.lua` needs to be added here:

```diff
diff --git a/lua/plugins/filetype.lua b/lua/plugins/filetype.lua
index ede9fd4..b35551d 100644
--- a/lua/plugins/filetype.lua
+++ b/lua/plugins/filetype.lua
@@ -497,7 +497,7 @@ vis.events.subscribe(vis.events.WIN_OPEN, function(win)
                for _, cmd in pairs(filetype.cmd or {}) do
                        vis:command(cmd)
                end
-               local path = vis.lexers.property['lexer.lpeg.home']:gsub(';', '/?.lua;') .. '/?.lua'
+               local path = vis.lexers.property['scintillua.lexers']:gsub(';', '/?.lua;') .. '/?.lua'
```

I think some logic in [vis.lua](https://github.com/mcepl/vis/blob/update_scintillua/lua/vis.lua#L266-L290) needs to be updated because the `lexer` table contents were overhauled. 

For reference, I dumped the previous contents of `lexer` (which `vis.lua` is currently written against) and the new content of `lexer` that is populated when I open `vis.c`:
[previous `lexer` table contents](https://paste.sr.ht/~eskin/da53ecde822a8b6970b2f4e232d22df4c8ca6bf9)
[new `lexer` table contents](https://paste.sr.ht/~eskin/2038fcd0b457f0ceb4f17ea01c644a56b649ead3)

Not sure how much other stuff there is, just ran out of time and wanted to dump out what I saw so far.

**Comment by mcepl** [comment]
> For one thing it looks like [a change from upstream](https://github.com/orbitalquark/scintillua/commit/b1f72de6af355514ef0a394620aff86901ebfcc2) to `lexer.lua` needs to be added here:
> 
> ```diff
> diff --git a/lua/plugins/filetype.lua b/lua/plugins/filetype.lua
> index ede9fd4..b35551d 100644
> --- a/lua/plugins/filetype.lua
> +++ b/lua/plugins/filetype.lua
> @@ -497,7 +497,7 @@ vis.events.subscribe(vis.events.WIN_OPEN, function(win)
>                 for _, cmd in pairs(filetype.cmd or {}) do
>                         vis:command(cmd)
>                 end
> -               local path = vis.lexers.property['lexer.lpeg.home']:gsub(';', '/?.lua;') .. '/?.lua'
> +               local path = vis.lexers.property['scintillua.lexers']:gsub(';', '/?.lua;') .. '/?.lua'
> ```

Unfortunately, it is not enough, I am afraid.

**Comment by mcepl** [comment]
I really didn’t want to close it. Not sure how I have managed to do it.

**Comment by mcepl** [comment]
@rnpnr Not sure whether I should ask you to reopen this one, or whether I should try again with the new tag [scintillua_6.2](https://github.com/orbitalquark/scintillua/releases/tag/scintillua_6.2).

**Comment by rnpnr** [comment]
I can't actually reopen this one since you deleted your github fork
of vis. However a new version based on Scintillua 6.2 would be very
appreciated.

**Comment by mcepl** [comment]
I will probably split it into multiple submissions and send to https://lists.sr.ht/~martanne/devel

**Comment by rnpnr** [comment]
Sounds good to me.

To answer your upstream question (https://github.com/orbitalquark/scintillua/issues/87#issuecomment-1446540510), based on:

> Table contents dumped when opening `vis.c`:
> 
> [old](https://paste.sr.ht/~eskin/da53ecde822a8b6970b2f4e232d22df4c8ca6bf9) [new](https://paste.sr.ht/~eskin/2038fcd0b457f0ceb4f17ea01c644a56b649ead3)

It looks like replacing `_TOKENSTYLES` with `_TAGS` might be
sufficient. Otherwise some of the logic in `vis.lua` will need to
be updated.

**Pull request closed without merging**
