### PR TITLE
Revert "fix bug where visual-line selections after view were consider…

### PR DESCRIPTION
**Pull request by erf**
…ed visible"

This reverts commit c22b2c2937d9dd65d0609e57f948f08da7f5c5ea.

Fixes issue #1084

### CODE REVIEW

**Review by mcepl — APPROVED** [review]
Yes, this commit helped me to get back fully working vis. THank you!

**Comment by mcepl** [comment]
Merged into https://git.sr.ht/~mcepl/vis/tree and it seems to be working.

**Comment by rnpnr** [comment]
Just to reiterate the correct fix seems to be #1087 which maintains the fix for #1074 and fixes the issues introduced by c22b2c2. I don't think reverting c22b2c2 is correct.

**Comment by mcepl** [comment]
> Just to reiterate the correct fix seems to be #1087 which maintains the fix for #1074 and fixes the issues introduced by [c22b2c2](https://github.com/martanne/vis/commit/c22b2c2937d9dd65d0609e57f948f08da7f5c5ea). I don't think reverting [c22b2c2](https://github.com/martanne/vis/commit/c22b2c2937d9dd65d0609e57f948f08da7f5c5ea) is correct.

You are completely right, and this particular PR should be closed and abandoned.

**Review by mcepl — CHANGES_REQUESTED** [review]
This is wrong approach, @rnpnr is right, the correct way is #1087 . This PR should be closed and abandoned.

**Pull request closed without merging**
