### PR TITLE
README.md: Do you want a table of content?

### PR DESCRIPTION
**Pull request by josuah**
I added a table of content, and checked every link in the browser.

### CODE REVIEW

**Comment by sshbio** [comment]
There is now also the logo in the pull request.  This is just to show how the page look with it.

**Comment by martanne** [comment]
Hi, I agree the current README is a mess, mixing end user "documentation", extension interfaces and editor internal design decisions. Marketing could certainly be improved ;-) Also because it has become so long, it would benefit from a table of content. However manually duplicating all section headings can't be the optimal way to achieve that. Markdown is probably just not the right format for this kind of thing.

Eventually the README should just contain some bullet points describing overall design goals, a screen cast, a logo and pointers to properly formatted further resources (e.g. a LaTeX based report, manual pages, generated Lua API docs etc.).

**Comment by josuah** [comment]
I think splitting it like you suggested would be good.

With the current content, this could be something like:

### `README.md`
*~160 lines*

  - Introuction at the top like it is now
  - Where to get info (links to other documents).
  - Getting started / Build instructions
  - Goals/Non-Goals 

### `TODO.md`
*~50 lines*, but could grow fast

  - Future plan / Ideas 

### `LUA API`
*~70 lines*  Self-generated from [LDoc](https://github.com/stevedonovan/LDoc)?

### `FEATURES.md`
*~470 lines*

  - The default keybindings and the behavior
  - The commands for the command line prompt

### `CONTRIBUTE.md`
*~210 lines*

  - Text management using a piece table/chain
  - Syntax Highlighting using Parsing Expression Grammars
  - Developer Overview

**Comment by josuah** [comment]
If this scheme suits you, I can try to

- convert the FEATURES.md into a man page and generate markdown from it with Pandoc,
- get started with `LDoc`.

**Comment by martanne** [comment]
Yes these two things (generated Lua API docs and a proper mdoc formatted manual page) would be useful anyway, independently of how we end up structuring the README. Once we are happy with these external parts, we can remove them from the README.

**Comment by josuah** [comment]
I made the pull request for the man page (#394), now about the LDoc lua API: do you want some automation with travis like for [this repo](https://github.com/JakobOvrum/LuaIRC)?

**Comment by martanne** [comment]
Automatically updating the docs would be nice, but unrelated. As a first step I would introduce a new Makefile target which generates the docs locally.

**Pull request closed without merging**
