### PR TITLE
Add csproj and psm1 extensions to filetype

### PR DESCRIPTION
**Pull request by milhnl**
Hey all, just a small change, so not much to comment.

### CODE REVIEW

**Review by rnpnr — COMMENTED** [review]
I'll say yes to the `.psm1` type but no to the `.csproj` type. The
latter seems to be auto-generated and mostly used by vscode. I don't
really think supporting every random auto-generated file from other text
editors makes any sense for vis.

You can easily add support for it locally in `visrc.lua`, just put this
somewhere after `require('vis')`:

```lua
table.insert(vis.ftdetect.filetypes.xml.ext, "%.csproj$")
```

**Comment by milhnl** [comment]
I'm ok with not adding it, but I (and others working with dotnet projects) do need to edit it by hand, so if that makes you reconsider, great. The modification for my visrc you propose is already in there, but yours is more efficient. Thanks :)

**Comment by mcepl** [comment]
On Mon Sep 18, 2023 at 7:16 PM CEST, Randy Palamar wrote:
> I'll say yes to the `.psm1` type but no to the `.csproj` type. The
> latter seems to be auto-generated and mostly used by vscode. I don't
> really think supporting every random auto-generated file from other text
> editors makes any sense for vis.

Just +1 for this decision from me.

-- 
https://matej.ceplovi.cz/blog/, Jabber: ***@***.***
GPG Finger: 3C76 A027 CA45 AD70 98B5  BC1D 7920 5802 880B C9D8
 
I’ve never seen God worried yet.
  -- Wm. Paul Young

**Comment by milhnl** [comment]
Sure. But the reasoning is still incorrect.

**Comment by rnpnr** [comment]
I just pushed 7367ea8 which should also cover your csproj file.

Thanks for the patch!

**Comment by milhnl** [comment]
Smart. Thanks. `file` says it's `text/plain` on my system but that's not vis' problem.

**Pull request closed without merging**
