### PR TITLE
Add Gleam Language

### PR DESCRIPTION
**Pull request by tynanbe**
Adds Gleam lexer and filetype detection.

PR submitted upstream for Gleam lexer:
https://github.com/orbitalquark/scintillua/pull/44

See:
- https://github.com/gleam-lang/
- https://gleam.run/

### CODE REVIEW

**Comment by mcepl** [comment]
This PR should be probably split. I see that your PR to scintillua has been accepted, so vis needs only change in `lua/plugins/filetype.lua`.

**Comment by tynanbe** [comment]
@mcepl Looks like `scintillua` updated the format (https://github.com/orbitalquark/scintillua/pull/44#issuecomment-789317337). Are scintillua's "non-legacy" lexers being pulled in and used in `vis` now?

**Comment by mcepl** [comment]
> @mcepl Looks like `scintillua` updated the format ([orbitalquark/scintillua#44 (comment)](https://github.com/orbitalquark/scintillua/pull/44#issuecomment-789317337)). Are scintillua's "non-legacy" lexers being pulled in and used in `vis` now?

We are working (in #1018)  on switching to the current non-legacy scintillua lexers.

**Comment by ninewise** [comment]
merged in b828b5b986a576196cda2ccba13579de96772ebd, thanks!

**Pull request closed without merging**
