### PR TITLE
lua: refactor complete-filename plugin

### LINKED ISSUE #1146: Complete file name and file path swapped in doc
Doing `:help` gives me this:

```
<C-x><C-f>            Complete file path                                                                                                                                                                                             
<C-x><C-o>            Complete file name
```

Trying myself, it seems it is the opposite in fact:

```
<C-x><C-f>            Complete file name                                                                                                                                                                                             
<C-x><C-o>            Complete file path
```

I don't know if it is the implementation or doc that is wrong.

### PR DESCRIPTION
**Pull request by rnpnr**
There are probably more things to simplify but at least this makes it easier to see what exactly is different between `<C-x><C-f>` and `<C-x><C-o>`.

closes #1146

Comments on how to simplify this more would be appreciated!

### CODE REVIEW

**Comment by mcepl** [comment]
I have now rebased that patch by João on the top of this PR as https://git.sr.ht/~mcepl/vis/commit/09e25541cace.

**Comment by rnpnr** [comment]
I made a couple changes to remove some differences between the two modes:
* whitespace in range is treated the same for both actions
* empty range will expand to files in PWD for both actions
For the second point `vis-complete` has some edge case that causes the name of the current directory to be added if invoked as `vis-complete --file ''` but that can be fixed separately.

**Comment by rnpnr** [comment]
> I have now rebased that patch by João on the top of this PR as https://git.sr.ht/~mcepl/vis/commit/09e25541cace

Thinking about it again this doesn't belong in `complete-filename.lua` . It should be made in `vis-open` just like how `vis-complete` handles `~` separately.

**Comment by mcepl** [comment]
> > I have now rebased that patch by João on the top of this PR as https://git.sr.ht/~mcepl/vis/commit/09e25541cace
> 
> Thinking about it again this doesn't belong in `complete-filename.lua` . It should be made in `vis-open` just like how `vis-complete` handles `~` separately.

Looking at the code:

```lua
        local cmdfmt = "vis-complete --file '%s'"
 	if expand then cmdfmt = "vis-open -- '%s'*" end
```

Shouldn’t be fixed in both?

**Comment by rnpnr** [comment]
> Shouldn’t be fixed in both?

Sorry I mean in the shell scripts themselves. `vis-complete` already handles it. It just needs to be added to `vis-open`.

**Comment by mcepl** [comment]
> > Shouldn’t be fixed in both?
> 
> Sorry I mean in the shell scripts themselves. `vis-complete` already handles it. It just needs to be added to `vis-open`.

Actually, can you reproduce it? Even without João’s commit, `vis-open ~/.bashrc` does what it should?

**Comment by mcepl** [comment]
> because `~` isn't expanded before being passed to `vis-open`

And why should it matter when I have shown that `vis-open ~/filename` works as expected?

**Comment by rnpnr** [comment]
> why should it matter when I have shown that `vis-open ~/filename` works as expected?

It doesn't if invoked inside vis. Open a new file and do `i~/<C-x><C-f>` and it will expand to your home directory. Now do `i~/<C-x><C-o>` and nothing will happen.

**Pull request merged**
