### PR TITLE
Add support for the Hare language file type

### PR DESCRIPTION
**Pull request by qiu-x**
https://harelang.org

### CODE REVIEW

**Comment by MuhammedZakir** [comment]
Lexers are fetched from upstream: https://github.com/orbitalquark/scintillua/. You should open the PR there.

**Comment by qiu-x** [comment]
I see, thanks for the info. And what about the changes in `lua/plugins/filetype.lua`? I think that those are still necessary here.

**Comment by jgarte** [comment]
> Lexers are fetched from upstream: https://github.com/orbitalquark/scintillua/. You should open the PR there.

Would it be possible to install the lexers from [orbitalquark](https://github.com/orbitalquark/scintillua/) instead of vendoring them in?

**Comment by MuhammedZakir** [comment]
> I see, thanks for the info.

You're welcome!

> And what about the changes in `lua/plugins/filetype.lua`? I think that those are still necessary here.

Changes to that should be made here.

> > Lexers are fetched from upstream: https://github.com/orbitalquark/scintillua/. You should open the PR there.
> 
> Would it be possible to install the lexers from [orbitalquark](https://github.com/orbitalquark/scintillua/) instead of vendoring them in?

I think it was done this way for bundling everything together, which makes installing easy. Another important advantage is that, if the upstream made any backward-incompatible changes, you can prevent `vis` from breaking, which is not possible if lexers are directly fetched from upstream.

**Comment by ninewise** [comment]
Applied in eb96e0ce8143804f5a7a37eb76a4b86d8871dd76

**Pull request closed without merging**
