### PR TITLE
Typst lexer

### PR DESCRIPTION
**Pull request by Disonantemus**
Bad, but better than nothing.

### CODE REVIEW

**Comment by mcepl** [comment]
Please, submit the new lexer to the upstream https://github.com/orbitalquark/scintillua, who maintains them (and who have much better experience with their design). We are just taking them from there.

**Comment by rnpnr** [comment]
Exactly as mcepl says. I will happily merge it if its accepted there.

Its too much of a maintenance burden for us to manage changes to the lexers here. We already accidentally deleted local changes last time we synced with upstream.

**Comment by mcepl** [comment]
On Thu Mar 14, 2024 at 2:37 PM CET, Randy Palamar wrote:
> Exactly as mcepl says. I will happily merge it if its accepted there.
>
> Its too much of a maintenance burden for us to manage changes to the lexers here. We already accidentally deleted local changes last time we synced with upstream.

That was slightly too fast, wasn’t it? Changes to plugins/filetype.lua should be accepted.

-- 
http://matej.ceplovi.cz/blog/, @***@***.***
GPG Finger: 3C76 A027 CA45 AD70 98B5  BC1D 7920 5802 880B C9D8
 
Every developer’s hunt for the best editor ends up with Vim,
Emacs or a management position.
  -- Rolf Bjaanes

**Comment by rnpnr** [comment]
> That was slightly too fast, wasn’t it? Changes to plugins/filetype.lua should be accepted.

Oops you are right. I applied that part here 8fccd1b.

**Pull request closed without merging**
