### PR TITLE
include https as link in markdown

### PR DESCRIPTION
**Pull request by erf**
include https as link in markdown. maybe there is a more clever way of doing this..?

### CODE REVIEW

**Comment by martanne** [comment]
Maybe @TieDyedDevil could take a general look at the markdown syntax definition as he is the de facto maintainer for the syntax highlighting definitions. As an example in vis's README.md the diagrams which are indented by 4 spaces are colored improperly (whether it makes sense at all to highlight them is another question) ...

**Comment by erf** [comment]
👍

**Comment by TieDyedDevil** [comment]
Ah. Sorry. I missed this the first time around.

Yes, this change should be fine for the purpose of treating an http link the same as an https link.

The only thing I'd ask is: Might it make sense to generalize this further to give all URIs the same treatment, regardless of method? IOW, would it make sense to match the method (e.g. http, https, ftp, webdav, ...) using a wildcard?

**Comment by erf** [comment]
Why not all links on the format of []() ?

**Comment by erf** [comment]
Hmm.. I see atom and neovim only highlights url's if they are of type `[]()`

**Comment by apotheon** [comment]
That's because URIs are not syntactically significant to Markdown except as contents of Markdown link hints.  Did I miss discussion of the reason URIs should be highlit universally in Markdown?

**Comment by erf** [comment]
I think only markdown links `[]()` should be highlighted, not URI's

**Comment by martanne** [comment]
Since the 'correct' thing to do largely depends on personal taste, I chose to remain compatible with the upstream scintillua project.

**Pull request closed without merging**
