### PR TITLE
Add lexer for Janet

### PR DESCRIPTION
**Pull request by sevvie**
All I did was copy the clojure.lua file over, change the appropriate parts of the file, and added janet to the filetype.lua core plugin because I needed it; I figured others might want it too.

### CODE REVIEW

**Comment by mcepl** [comment]
Lexers are fetched from upstream: https://github.com/orbitalquark/scintillua/. You should open the PR there.

**Comment by sevvie** [comment]
https://github.com/orbitalquark/scintillua/pull/66

I've taken the lexer out of this PR and moved it to a PR on scintillua.

**Comment by jgarte** [comment]
> Lexers are fetched from upstream: https://github.com/orbitalquark/scintillua/. You should open the PR there.

How are lexers fetched from upstream? Is a script used or just manually?

**Comment by mcepl** [comment]
> > Lexers are fetched from upstream: https://github.com/orbitalquark/scintillua/. You should open the PR there.
> 
> How are lexers fetched from upstream? Is a script used or just manually?

It's actually more complicated than that. The problem is that vis actually supports only old deprecated API for scintillua.

* Currently there is unfinished branch [scintillua](https://github.com/martanne/vis/tree/scintillua) with the updates, but it has been last touched in 2021 and it doesn’t currently apply cleanly on the top of the current `master` branch and it doesn’t contain the current version of `scintillua` API (yes, I tried).
* Martanne’s reaction to the new API was [not enthusiastic (to say it mildly)](https://github.com/martanne/vis/issues/908#issuecomment-742487283), but later in the ticket he seemed to give in.
* There is current fresh PR to refresh API #1018, which I need to investigate.

It's a mess.

**Pull request closed without merging**
