### PR TITLE
Added @martanne's vis-digraphs program from #460

### PR DESCRIPTION
**Pull request by josuah**
I am not sure if this is how you want to integrate it to the tree, so feel free to adjust (or to ask me to do so).

This works for digraphs (not for more than 2 characters):

```
make clean
./configure
make
./vis
i<c-k>L*
```

### CODE REVIEW

**Comment by martanne** [comment]
Thanks, some preliminary comments. I will try to take a closer look later on:

* I would prefer if `vis-digraph.h` would be merged directly into `vis-digraph.c`
* The man page has some issues
  - The characters are not necessarily UTF-8 but output according to the user locale
  - The various exit status should be mentioned
  - The `$LC_CTYPE` environment variable should probably be mentioned
  - Just mentioning standard input is enough, no need to talk about interactive keyboard input etc
  -  Some unrelated parts from `vis-menu` seem to have crept in? Run `make man` and proof read & check the formatting in a browser.

You can force push these changes into the corresponding patches.

Also what is the problem with digraphs longer than 2 characters? (This should probably be discussed in the issue?)

**Comment by josuah** [comment]
I am making these changes.

I do not know if I can fill the multiple commits with appropriate changes, but I can merge them all in one commit.

**Comment by josuah** [comment]
My bad, `vis-digraph` works everywhere and for any length of char.  I just had to recompile the with data from the RFC.

**Comment by martanne** [comment]
Thanks! I merged your stuff with a different commit message (github handles aren't really descriptive) and some slight white space tweaks. The author section of the man page was removed and vis-digraph is now also referenced from `vis.1`.

**Comment by josuah** [comment]
You are welcome, and thank you for fixing it all up.

**Pull request closed without merging**
