### PR TITLE
ci: install busted to run lua tests

### PR DESCRIPTION
**Pull request by fischerling**
Install busted in the CI pipelines to run the included lua tests.

### CODE REVIEW

**Review by rnpnr — APPROVED** [review]
> vis 788e9b8 +curses +lua +tre
cursor                        OK
lines                         OK
map-basic                     OK
file-empty                    OK
Tests ok 4/4

Thanks! Applying!

**Comment by fischerling** [comment]
> > vis [788e9b8](https://github.com/martanne/vis/commit/788e9b86631b8f16bb5309d9be5ca382eb4797c0) +curses +lua +tre
> > cursor                        OK
> > lines                         OK
> > map-basic                     OK
> > file-empty                    OK
> > Tests ok 4/4

Unfortunatly this does not mean that all tests passed.
For all those not watching the mailing list.
[Bug report on the mailing list](https://lists.sr.ht/~martanne/devel/%3Cbjhspuvyw7v3ct6bnqfht4q7ragh74jbrpvgtpitbdh4ppg3p6@36igdrqbv36v%3E)

**Comment by fischerling** [comment]
Maybe we should apply https://github.com/jeremybobbin/vis-test/commit/db8210daa4e9fa17bea4a31aa15b71a786e85902 and drop busted altogether.

Alternativly, if we want to keep busted, there is https://github.com/fischerling/vis/commit/dab1f4a6973d12a0936356918c2611b4b5e5a51c to fix the test failure detection.

**Comment by mcepl** [comment]
On Tue Sep 10, 2024 at 10:25 AM CEST, fischerling wrote:
> Maybe we should apply https://github.com/jeremybobbin/vis-test/commit/db8210daa4e9fa17bea4a31aa15b71a786e85902 and drop busted altogether.

I am all for it, less dependencies better.

Best,

Matěj

-- 
http://matej.ceplovi.cz/blog/, @***@***.***
GPG Finger: 3C76 A027 CA45 AD70 98B5  BC1D 7920 5802 880B C9D8
 
“Goodbye,” said the fox. “And now here is my secret, a very
simple secret: It is only with the heart that one can see
rightly; what is essential is invisible to the eye.”
   -- Antoine de Saint-Exupery

**Comment by rnpnr** [comment]
The reason I didn't apply it was because Jeremy said he wasn't entirely happy with it. I'm not really seeing any particular issue with it. I'll confirm on the mailing list.

**Pull request merged**
