### PR TITLE
Sync scintilua repo

### PR DESCRIPTION
**Pull request by Nomarian**
It works, but I'm not confident in the branch itself, basically copied every file from scintilua to the lexers folder, copied lexer.lua moved it into plugins/ and changed a bit so it actually works with vis.lua.

lpeg is now a global as well.

Do not merge until MUCH testing.

### CODE REVIEW

**Comment by mcepl** [comment]
Despite continuing work upstream on improving our lexers, I don’t see anything stopping us from merging this.

**Review by mcepl — APPROVED** [review]
Despite continuing work upstream on improving our lexers, I don’t see anything stopping us from merging this.

**Comment by Nomarian** [comment]
html is broken.

**Comment by mcepl** [comment]
So, closing this in favour of #1018? Is there something which needs to be transferred there?

**Comment by qiu-x** [comment]
Yes, if anything needs to be transferred we can continue the discussion in #1018

**Comment by mcepl** [comment]
So, could you close this PR, please, to make @ninewise happy. You don’t want to make him unhappy, don’t you?

**Pull request closed without merging**
