### PR TITLE
add .clang-format code format file

### PR DESCRIPTION
**Pull request by sheeaza**
~~'.cache' and 'compile_commands.json' are used by clangd~~

~~Signed-off-by: sheeaza <winsdenny@outlook.com>~~

### CODE REVIEW

**Comment by ninewise** [comment]
IMHO editor/compiler-specific files belong in your global gitignore/configuration, not in each project you edit with it. On the other hand, there are already vi-specific files in the gitignore.

**Comment by sheeaza** [comment]
so what about the .clang-format commit for code format

**Comment by ninewise** [comment]
That's up to the maintainer, I guess.

**Comment by martanne** [comment]
I agree with @ninewise that editor specific files should be kept out of the repository.

As stated elsewhere I am not a big fan of whitespace only changes. They cause unnecessary merge conflicts and clutter source control history etc. Adding configuration for source formatting and then not enforcing it also doesn't make much sense. Therefore I'm closing this for now.

**Pull request closed without merging**
