### PR TITLE
set view to bottom of selection

### PR DESCRIPTION
**Pull request by erf**
This seems to work as desired and disscused in #164 and #274 - could you have a look?

### CODE REVIEW

**Comment by martanne** [comment]
The idea behind these changes was to show more context *around* the new cursor location. Hence why we attempt to place the cursor in the middle of the screen such that relevant context both before and afterwards is visible.

You will have to make a better case for why you want your proposed behavior. It does not seem to be an improvement to me.

**Comment by erf** [comment]
I believe the behavour i propose is the default in other editors. Also you can see more of the text you are working on (selected).

**Comment by erf** [comment]
Not sure this pull request still work but i found another case which support the proposed behaviour - that is if you have a line that wraps over multiple lines that exceeds the bottom of the screen, if you are at the start of that line and press `j`, it skips the whole line, so you are not able to read it, except if you traverse it by word/char.

**Comment by apotheon** [comment]
What happens in the case that the selected text height is greater than the height of the screen?

**Comment by erf** [comment]
The most important case for me regarding the current view change behaviour, is that when i scroll up or down with `j` and `k`, i loose context of where i am in the document when the view skips up or down half a page - i find it a bit confusing. Maybe the view-change behavour could be configured in the visrc file, with an option to move up/down one line at a time?

**Comment by erf** [comment]
You could also implement vim's `scrolloff` option, which sets "Minimal number of screen lines to keep above and below the cursor.".

http://vimdoc.sourceforge.net/htmldoc/options.html#%27scrolloff%27

**Pull request closed without merging**
